server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tp_java
    username: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    ma.pfe: ERROR